import type { VideoDetail, VideoListItem, VideoSource } from "./video-types";

export const mockVideoSources: VideoSource[] = [
  {
    id: "video-source-product",
    title: "产品沉思录",
    url: "https://space.bilibili.com/10001",
    type: "video",
    platform: "bilibili",
    favicon: null,
    unreadCount: 2,
    lastFetchedAt: "2026-07-12T08:20:00.000Z",
  },
  {
    id: "video-source-ai",
    title: "AI Builder Lab",
    url: "https://www.youtube.com/@aibuilderlab",
    type: "video",
    platform: "youtube",
    favicon: null,
    unreadCount: 1,
    lastFetchedAt: "2026-07-12T07:40:00.000Z",
  },
];

export const mockVideoDetails: VideoDetail[] = [
  {
    id: "video-entry-memory",
    sourceId: "video-source-product",
    platform: "bilibili",
    title: "AI 产品真正的壁垒，可能不是模型而是记忆",
    url: "https://www.bilibili.com/video/BV1mock001",
    creatorName: "产品沉思录",
    durationSeconds: 596,
    publishedAt: "2026-07-12T06:30:00.000Z",
    summary:
      "视频从信息收集、长期记忆和主动回顾三个层面，分析 AI 产品如何从一次性工具变成持续理解用户的个人系统。",
    processingStatus: "ready",
    watchStatus: "watching",
    progressSeconds: 120,
    isFavorited: true,
    coverImage: "https://storage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg",
    mockVideoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    quickJudgment: {
      summary: "这期视频认为，当模型能力逐渐同质化，AI 产品真正能积累的壁垒会转向长期记忆：持续理解用户、允许用户校正，并在恰当时机主动唤回过去的信息。",
      highlights: [
        "信息管理不只是在收集，还包括理解，以及在需要时重新呈现。",
        "显式收藏代表明确意图，隐式推断必须提供确认、修改和删除能力。",
        "摘要只有进入新的写作、决策或项目，才真正从库存变成知识。",
      ],
      thoughts: [
        "如果记忆是产品壁垒，用户是否应该能看到一份完整的“AI 对我的理解”？",
        "主动回顾的核心指标，可能不是打开率，而是它是否帮助用户完成了下一步行动。",
      ],
      terms: [
        { term: "长期记忆", explanation: "跨会话保存并可再次调用的用户事实、偏好、关系与历史上下文。" },
        { term: "主动回顾", explanation: "系统根据当前场景和时机，主动把过去有价值的信息重新带回用户面前。" },
      ],
    },
    targetAudience: "正在设计 AI 助手、知识管理或长期用户记忆产品的产品经理。",
    keyPoints: [
      "模型能力会逐渐同质化，长期记忆更可能形成产品体验差异。",
      "收集不是终点，能否在合适时间重新呈现信息决定知识是否真正有用。",
      "记忆系统需要让用户理解、修正并控制 AI 保存的内容。",
    ],
    chapters: [
      { id: "chapter-1", startSeconds: 0, endSeconds: 85, title: "为什么模型不再是唯一壁垒", theme: "产品壁垒", summary: "从模型能力快速扩散讲到产品差异化正在转向用户上下文。" },
      { id: "chapter-2", startSeconds: 85, endSeconds: 190, title: "信息管理产品的三个层次", theme: "信息价值", summary: "区分收集、理解和重新呈现，指出大多数工具停留在第一层。" },
      { id: "chapter-3", startSeconds: 190, endSeconds: 330, title: "AI 记忆应该如何建立", theme: "记忆控制", summary: "讨论显式保存、隐式推断、用户确认和可撤销性。" },
      { id: "chapter-4", startSeconds: 330, endSeconds: 465, title: "主动回顾比自动总结更重要", theme: "信息价值", summary: "总结只有被重新使用时才产生价值，触发时机比摘要长度更关键。" },
      { id: "chapter-5", startSeconds: 465, endSeconds: null, title: "给早期产品的落地建议", theme: "产品壁垒", summary: "建议先验证一个高频记忆闭环，而不是一开始建立全能知识图谱。" },
    ],
    transcript: [
      { id: "segment-1", startSeconds: 0, endSeconds: 18, text: "今天想讨论一个问题，AI 产品真正能够长期留下用户的东西到底是什么。" },
      { id: "segment-2", startSeconds: 38, endSeconds: 62, text: "如果所有团队最终都能调用到接近的模型能力，那么模型本身很难成为永久壁垒。" },
      { id: "segment-3", startSeconds: 92, endSeconds: 118, text: "信息管理可以分成收集、理解和重新呈现三个层次，很多产品只完成了第一个。" },
      { id: "segment-4", startSeconds: 142, endSeconds: 172, text: "用户真正需要的不是更多摘要，而是在做决定时重新遇到过去有价值的信息。" },
      { id: "segment-5", startSeconds: 205, endSeconds: 238, text: "记忆不能完全是黑盒，用户必须知道系统记住了什么，也要能够修改和删除。" },
      { id: "segment-6", startSeconds: 272, endSeconds: 304, text: "显式收藏代表用户意图，隐式推断则需要更谨慎的确认机制。" },
      { id: "segment-7", startSeconds: 346, endSeconds: 378, text: "主动回顾的难点不是生成内容，而是找到不打扰用户又真正有用的时机。" },
      { id: "segment-8", startSeconds: 408, endSeconds: 442, text: "当一条信息能够进入新的写作、决策或者项目，它才从库存变成了可以使用的知识。" },
      { id: "segment-9", startSeconds: 478, endSeconds: 510, text: "早期产品不需要建立完美记忆，先让一个具体场景形成闭环更重要。" },
      { id: "segment-10", startSeconds: 548, endSeconds: 580, text: "最后总结，模型负责理解，产品负责关系，而记忆连接了两者。" },
    ],
    highlights: [
      { id: "highlight-1", startSeconds: 92, title: "信息管理的三层模型", note: "收集只是入口，理解和重新呈现才决定长期价值。", score: 86 },
      { id: "highlight-2", startSeconds: 205, title: "记忆必须可控制", note: "让用户知道系统记住了什么，并提供修正与删除能力。", score: 92 },
      { id: "highlight-3", startSeconds: 408, title: "库存如何变成知识", note: "信息进入新的决策、写作或项目时，才真正完成沉淀。", score: 89 },
    ],
    visualSummary: [
      { id: "visual-1", eyebrow: "输入", title: "持续收集", detail: "笔记、剪藏、订阅与对话形成长期上下文。" },
      { id: "visual-2", eyebrow: "理解", title: "用户可控记忆", detail: "AI 提取关系，但保存、修正和删除权属于用户。" },
      { id: "visual-3", eyebrow: "输出", title: "主动重新呈现", detail: "在写作和决策时，把过去的信息重新带回现场。" },
    ],
  },
  {
    id: "video-entry-agent",
    sourceId: "video-source-ai",
    platform: "youtube",
    title: "Building a Personal Knowledge Agent from Scratch",
    url: "https://www.youtube.com/watch?v=mock002",
    creatorName: "AI Builder Lab",
    durationSeconds: 653,
    publishedAt: "2026-07-11T14:10:00.000Z",
    summary: null,
    processingStatus: "analyzing",
    watchStatus: "unwatched",
    progressSeconds: 0,
    isFavorited: false,
    coverImage: "https://storage.googleapis.com/gtv-videos-bucket/sample/images/ElephantsDream.jpg",
    mockVideoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    quickJudgment: null,
    targetAudience: null,
    keyPoints: [],
    chapters: [],
    transcript: [
      { id: "agent-segment-1", startSeconds: 0, endSeconds: 22, text: "In this video we will build a small personal knowledge agent from the ground up." },
      { id: "agent-segment-2", startSeconds: 132, endSeconds: 165, text: "The first decision is what data should become durable memory and what should remain temporary context." },
      { id: "agent-segment-3", startSeconds: 420, endSeconds: 458, text: "Retrieval quality depends more on clean boundaries and useful metadata than on adding more tools." },
    ],
    highlights: [],
    visualSummary: [],
  },
  {
    id: "video-entry-research",
    sourceId: "video-source-product",
    platform: "bilibili",
    title: "从用户访谈到产品判断：一次真实研究复盘",
    url: "https://www.bilibili.com/video/BV1mock003",
    creatorName: "产品沉思录",
    durationSeconds: 15,
    publishedAt: "2026-07-10T09:20:00.000Z",
    summary: "字幕已获取，正在生成章节和关键观点。",
    processingStatus: "fetching_transcript",
    watchStatus: "unwatched",
    progressSeconds: 0,
    isFavorited: false,
    coverImage: "https://storage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg",
    mockVideoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    quickJudgment: null,
    targetAudience: null,
    keyPoints: [],
    chapters: [],
    transcript: [],
    highlights: [],
    visualSummary: [],
  },
  {
    id: "video-entry-weekly",
    sourceId: "video-source-ai",
    platform: "youtube",
    title: "AI Product Weekly: Agents, Memory and Evaluation",
    url: "https://www.youtube.com/watch?v=mock004",
    creatorName: "AI Builder Lab",
    durationSeconds: 888,
    publishedAt: "2026-07-09T16:00:00.000Z",
    summary: "平台没有提供可用字幕，当前只能展示视频信息。",
    processingStatus: "no_transcript",
    watchStatus: "watched",
    progressSeconds: 888,
    isFavorited: false,
    coverImage: "https://storage.googleapis.com/gtv-videos-bucket/sample/images/Sintel.jpg",
    mockVideoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    quickJudgment: null,
    targetAudience: null,
    keyPoints: [],
    chapters: [],
    transcript: [],
    highlights: [],
    visualSummary: [],
  },
];

export const mockVideoList: VideoListItem[] = mockVideoDetails.map(
  ({ quickJudgment: _quickJudgment, keyPoints: _keyPoints, targetAudience: _targetAudience, chapters: _chapters, transcript: _transcript, highlights: _highlights, visualSummary: _visualSummary, ...item }) => item,
);

export function mockVideoDetailById(id: string) {
  return mockVideoDetails.find((item) => item.id === id) ?? null;
}
